FORMAT: 1A
HOST: https://protected-gorge-44302.herokuapp.com

# rentSTHLM
Välkommen! På den här sidan hittar du API-dokumentationen för rentSTHLMs REST-API.

# Group Inloggning

## Facebook-inloggning [/facebook/login]

## Logga in en användare via Facebook. [POST]

+ Request (application/json)

    + Attributes
        + facebookAuthToken: `EAACEdEose0cBAIID5sKglHcm01UYAGWP0cHgDEcAxrbDg0oZAzZCZC1Tlhw62ZBkhqMO6imdMtcQJqDfAGc8bKl08Q1FrR0Vz7SgVWh9sMEqUkUow07a3Vk3LwdHBMZANCXeTTKrlQGz2jOuOQJwGFZAk8RnHGpd1nU6F36OGtxtqZC50m7gSfo` -
        En token för auktorisering mot Facebooks Graph API.
        
+ Response 200 (application/json)

    + Attributes
        + authToken: `990c4d5e-3764-4473-9525-f317dabf5dc2` - En token för vidare autentisering mot API:t.

# Group Användare

## Användare [/users{?id}]

## Hämta en användares profil. [GET]
+ Parameters
    + id: 2 (number, optional) - Observera att denna parameter endast är nödvändig om den användare som ska hämtas inte är den som identifieras av den token som skickas i headern. Denna token är tillräcklig för att identifiera användaren som gör requesten. Parametern är tänkt för att till exempel låta en hyresvärd hämta information om en hyresgäst.

+ Request

    + Headers
    
            X-AUTH-TOKEN: en valid autentiseringstoken.
        
+ Response 200 (application/json)

    + Attributes (LocalUser)

## Hyresgäst [/users/tenants]

## Hämta en hyresgästs profil. [GET]

+ Request

    + Headers
    
            X-AUTH-TOKEN: en valid autentiseringstoken

+ Response 200 (application/json)

    + Attributes (Tenant)

+ Response 401 (application/json)

    + Attributes
        + error: fel

## Uppdatera en hyresgästs profil. [PUT]

+ Request (application/json)

    + Headers
    
            X-AUTH-TOKEN: en valid autentiseringstoken

    + Attributes (Tenant)

+ Response 200 (application/json)
    + Attributes (Tenant)

## Hyresvärd [/users/renters]

## Hämta en hyresvärds profil. [GET]

+ Request

    + Headers
    
            X-AUTH-TOKEN: en valid autentiseringstoken

+ Response 200 (application/json)

    + Attributes (Renter)

## Uppdatera en hyresvärds profil. [PUT]

+ Request

    + Headers
    
            X-AUTH-TOKEN: en valid autentiseringstoken

    + Attributes (LocalUser)

+ Response 200 (application/json)

    + Attributes (LocalUser)

# Group Hyresobjekt 

## Hyresobjekt [/accommodation{?count,offset,id,rent,size,rooms,deposition,smokingAllowed,animalsAllowed,tv,broadband,start,end}]

## Hämta hyresobjekt. [GET]

+ Parameters
    + count: 10 (number, optional)
    + offset: 10 (number, optional)
    + id: 2 (number, optional)
    + rent: 5000 (number, optional)
    + size: 20 (number, optional)
    + rooms: 1 (number, optional)
    + deposition: 8000 (number, optional)
    + smokingAllowed: false (boolean, optional)
    + animalsAllowed: false (boolean, optional)
    + tv: true (boolean, optional)
    + broadband: true (boolean, optional)
    + start: `2017-05-01` (optional)
    + end: `2018-05-01` (optional)

+ Request

    + Headers
    
            X-AUTH-TOKEN: en valid autentiseringstoken

+ Response 200 (application/json)
    + Attributes (array[Accommodation])

## Skapa ett hyresobjekt. [POST]

+ Request (application/json)

    + Headers
    
            X-AUTH-TOKEN: en valid autentiseringstoken

    + Attributes (Accommodation)

+ Response 204

## Uppdatera ett hyresobjekt. [PUT]

+ Request (application/json)

    + Headers
    
            X-AUTH-TOKEN: en valid autentiseringstoken

    + Attributes (Accommodation)

+ Response 200 (application/json)

    + Attributes (Accommodation)

# Ta bort ett hyresobjekt. [DELETE]

+ Parameters
    + id: 1 (number, optional) - Denna parameter kommer bara att behövas om flera hyresobjekt per hyresvärd tillåts. Annars kan hyresobjektet identifieras av den token som skickats.

+ Request

    + Headers
    
            X-AUTH-TOKEN: en valid autentiseringstoken

+ Response 204

# Group Intresseanmälningar

## Intresseanmälningar [/interests{?count,offset,tenantId,accommodationId,mutual}]

## Hämta intresseanmälningar. [GET]

+ Parameters
    + count: 10 (number, optional)
    + offset: 10 (number, optional)
    + tenantId: 1 (number, optional)
    + accommodationId: 1 (number, optional)
    + mutual: false (boolean, optional)

+ Request

    + Headers
    
            X-AUTH-TOKEN: en valid autentiseringstoken

+ Response 200 (application/json)
    
    + Attributes (array[Interest])

## Skapa en intresseanmälan. [POST]

+ Request

    + Headers
    
            X-AUTH-TOKEN: en valid autentiseringstoken

    + Attributes (Interest)

+ Response 204

## Markera en intresseanmälan som antingen ömsesidig eller icke-ömsesidig. En nyskapad intresseanmälan är alltid icke-ömsesidig. [PUT]
 
+ Parameters
    + tenantId: 1 (number, required)
    + accommodationId: 1 (number, required)

+ Request

    + Headers
    
            X-AUTH-TOKEN: en valid autentiseringstoken

    + Attributes
        + mutual: false (boolean, required)

+ Response 200 

    + Attributes (Interest)

## Ångra en intresseanmälan. [DELETE]

+ Parameters
    + tenantId: 1 (number, required)
    + accommodationId: 1 (number, required)

+ Request

    + Headers
    
            X-AUTH-TOKEN: en valid autentiseringstoken

+ Response 204

## Data Structures

### FacebookUser
+ emailAddress: kalle@example.com
+ firstName: Kalle
+ lastName: Blomkvist
+ gender: male

### LocalUser (FacebookUser)
+ id: 2
+ images: bilder (array)


### Tenant (LocalUser)
+ description: `Hej, jag heter Kalle och behöver någonstans att bo.`
+ age: 23
+ numberoftenants: 1
+ income: 18000
+ maxrent: 5000
+ occupation: Karaktär i berättelse
+ deposition: 8000
+ rentalperiod
    + start: 2017-05-01
    + end: 2018-05-01

### Renter (LocalUser)
+ accommodation (Accommodation)

### Accommodation
+ rent: 5000
+ size: 20
+ rooms: 1
+ deposition: 8000
+ smokingAllowed: false (boolean)
+ animalsAllowed: false (boolean)
+ tv: true (boolean)
+ broadband: true (boolean)
+ description: `Schysst etta i lugnt område`
+ address (Address)

### Address
+ streetName: Dymlingsgränd
+ streetNumber: 3
+ streetNumberLetter: A
+ area: Hägerstensåsen
+ longitude: ""
+ latitude: ""

### Interest
+ tenantId: 1 (number, optional)
+ accommodationId: 1 (number, optional)
+ mutual: false (boolean, optional)